apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: exchange-api
  namespace: healthcare-exchange
spec:
  selector:
    matchLabels:
      app: exchange-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
