apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare-exchange

resources:
  - namespace.yaml
  - rbac.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - exchange-api.yaml
  - portal.yaml
  - backup-cronjob.yaml
  - networkpolicy.yaml
  - hpa.yaml
